services:
  api:
    build:
      context: .
      dockerfile: Devices.Api/Dockerfile
    container_name: devices-api
    ports:
      - "7217:7217"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7217
    volumes:
      - ./database:/app/data